[package]
name = "my-servers"
version = "0.7.1"
edition = "2024"
rust-version = "1.97"
license = "MIT OR Apache-2.0"
authors = ["Terakomari <im.terakomari@icloud.com>"]
repository = "https://github.com/TerakomariGandesblood/my-servers"
homepage = "https://github.com/TerakomariGandesblood/my-servers"
description = "A collection of servers"
readme = "README.md"
keywords = ["server", "http"]
categories = ["command-line-utilities"]

[lints.rust]
unsafe_code = "forbid"

[dependencies]
# https://github.com/purpleprotocol/mimalloc_rust
mimalloc = { version = "0.1.52", default-features = false }
# https://github.com/dtolnay/anyhow
anyhow = { version = "1.0.104", default-features = false, features = ["std"] }
# https://github.com/zkat/supports-color
supports-color = { version = "3.0.2", default-features = false }
# https://github.com/clap-rs/clap
clap = { version = "4.6.7", default-features = false, features = [
  "std",
  "color",
  "help",
  "usage",
  "error-context",
  "suggestions",
  "derive",
  "cargo",
  "wrap_help",
  "string",
] }
# https://github.com/clap-rs/clap-verbosity-flag
clap-verbosity-flag = { version = "3.0.4", default-features = false }
# https://github.com/clap-rs/clap/tree/master/clap_complete
clap_complete = { version = "4.6.11", default-features = false }
# https://github.com/clap-rs/clap/tree/master/clap_complete_nushell
clap_complete_nushell = { version = "4.6.2", default-features = false }
# https://github.com/tokio-rs/tracing/tree/main/tracing
tracing = { version = "0.1.44", default-features = false, features = [
  "std",
  "attributes",
] }
# https://github.com/tokio-rs/tracing/tree/main/tracing-subscriber
tracing-subscriber = { version = "0.3.23", default-features = false, features = [
  "std",
  "fmt",
  "ansi",
  "smallvec",
  "tracing-log",
  "env-filter",
  "json",
] }
# https://github.com/tokio-rs/tracing/tree/main/tracing-appender
tracing-appender = { version = "0.2.5", default-features = false }
# https://github.com/tokio-rs/tracing-opentelemetry
tracing-opentelemetry = { version = "0.33.0", default-features = false, features = [
  "tracing-log",
  "metrics",
] }
# https://github.com/open-telemetry/opentelemetry-rust/tree/main/opentelemetry
opentelemetry = { version = "0.32.0", default-features = false, features = [
  "trace",
  "metrics",
] }
# https://github.com/open-telemetry/opentelemetry-rust/tree/main/opentelemetry-sdk
opentelemetry_sdk = { version = "0.32.1", default-features = false, features = [
  "trace",
  "metrics",
] }
# https://github.com/open-telemetry/opentelemetry-rust/tree/main/opentelemetry-otlp
opentelemetry-otlp = { version = "0.32.0", default-features = false, features = [
  "trace",
  "metrics",
  "grpc-tonic",
  "http-proto",
  "reqwest-blocking-client",
] }
# https://github.com/open-telemetry/opentelemetry-rust/tree/main/opentelemetry-semantic-conventions
opentelemetry-semantic-conventions = { version = "0.32.1", default-features = false }
# https://github.com/tokio-rs/tokio-metrics
tokio-metrics = { version = "0.5.2", default-features = false, features = [
  "rt",
] }
# https://github.com/GuillaumeGomez/sysinfo
sysinfo = { version = "0.39.6", default-features = false, features = [
  "system",
] }
# https://github.com/serde-rs/serde/tree/master/serde
serde = { version = "1.0.229", default-features = false, features = [
  "std",
  "derive",
] }
# https://github.com/cloudwego/sonic-rs
sonic-rs = { version = "0.5.10", default-features = false }
# https://github.com/toml-rs/toml/tree/main/crates/toml
toml = { version = "1.1.6", default-features = false, features = [
  "std",
  "serde",
  "parse",
  "fast_hash",
] }
# https://github.com/servo/rust-url/tree/main/url
url = { version = "2.5.8", default-features = false, features = [
  "std",
  "serde",
] }
# https://github.com/kardeiz/sanitize-filename
sanitize-filename = { version = "0.6.0", default-features = false }
# https://github.com/BurntSushi/walkdir
walkdir = { version = "2.5.0", default-features = false }
# https://github.com/BurntSushi/jiff
jiff = { version = "0.2.37", default-features = false, features = [
  "std",
  "tz-system",
  "tz-fat",
  "tzdb-bundle-platform",
  "tzdb-zoneinfo",
  "tzdb-concatenated",
  "perf-inline",
  "serde",
] }
# https://github.com/tokio-rs/tokio/tree/master/tokio
tokio = { version = "1.53.1", default-features = false, features = [
  "macros",
  "signal",
  "time",
  "process",
  "rt-multi-thread",
] }
# https://github.com/tokio-rs/tokio/tree/master/tokio-util
tokio-util = { version = "0.7.19", default-features = false }
# https://github.com/rust-lang/futures-rs/blob/master/futures-util
futures-util = { version = "0.3.34", default-features = false, features = [
  "std",
] }
# https://github.com/tokio-rs/axum
axum = { version = "0.8.9", default-features = false, features = [
  "http2",
  "multipart",
  "tokio",
  "tower-log",
  "tracing",
  "matched-path",
] }
# https://github.com/tokio-rs/axum/blob/main/axum-extra
axum-extra = { version = "0.12.6", default-features = false, features = [
  "file-stream",
  "tracing",
] }
# https://github.com/programatik29/axum-server
axum-server = { version = "0.8.0", default-features = false, features = [
  "tls-rustls",
] }
# https://github.com/tower-rs/tower/tree/master/tower
tower = { version = "0.5.3", default-features = false, features = [
  "limit",
  "load-shed",
] }
# https://github.com/tower-rs/tower-http/tree/main/tower-http
tower-http = { version = "0.7.1", default-features = false, features = [
  "catch-panic",
  "compression-full",
  "csrf",
  "decompression-full",
  "fs",
  "on-early-drop",
  "request-id",
  "sensitive-headers",
  "timeout",
  "trace",
  "util",
] }
# https://github.com/seanmonstar/reqwest
reqwest = { version = "0.13.5", default-features = false, features = [
  "http2",
  "rustls",
  "gzip",
  "brotli",
  "zstd",
  "deflate",
  "json",
  "system-proxy",
] }
# https://github.com/harryfei/which-rs
which = { version = "8.0.6", default-features = false, features = ["real-sys"] }
# https://github.com/rusticstuff/simdutf8
simdutf8 = { version = "0.1.5", default-features = false, features = [
  "std",
  "aarch64_neon",
] }
# https://github.com/matklad/once_cell
once_cell = { version = "1.21.4", default-features = false, features = ["std"] }
# https://github.com/uuid-rs/uuid
uuid = { version = "1.26.1", default-features = false, features = [
  "std",
  "v4",
  "fast-rng",
] }
# https://github.com/krisprice/ipnet
ipnet = { version = "2.12.2", default-features = false, features = [
  "std",
  "serde",
] }
# https://github.com/imbolc/axum-client-ip
axum-client-ip = { version = "1.3.1", default-features = false, features = [
  "connect-info",
] }
# https://github.com/gengteng/axum-serde
axum-serde = { version = "0.10.0", default-features = false, features = [
  "sonic",
] }

[dev-dependencies]
# https://github.com/dbrgn/tracing-test/tree/main/tracing-test
tracing-test = { version = "0.2.6", default-features = false }
# https://github.com/wiktor-k/testresult
testresult = { version = "0.4.1", default-features = false }
